# Generated by Django 3.1.7 on 2021-04-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ImageField(null=True, upload_to='album/'),
        ),
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
